// Mock product data for development (replace with DB queries later)

export const mockProducts = [
  {
    id: 'p1',
    name: 'Ivory Chikankari Kurta with Palazzo',
    slug: 'ivory-chikankari-kurta-palazzo',
    sku: 'HFZ-CHK-001',
    price: 2499,
    comparePrice: 3999,
    totalStock: 12,
    isNewArrival: true,
    isBestSeller: false,
    isFeatured: true,
    isTrending: true,
    avgRating: 4.8,
    category: { name: 'Chikankari' },
    images: [
      { url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80', alt: 'Ivory Chikankari Kurta' },
      { url: 'https://images.unsplash.com/photo-1610030469668-93535c17b6b3?w=600&auto=format&fit=crop&q=80', alt: 'Ivory Chikankari Kurta Back' },
    ],
    variants: [
      { id: 'v1', size: 'XS', color: 'Ivory', colorHex: '#F5F0E8', stock: 2 },
      { id: 'v2', size: 'S', color: 'Ivory', colorHex: '#F5F0E8', stock: 4 },
      { id: 'v3', size: 'M', color: 'Ivory', colorHex: '#F5F0E8', stock: 3 },
      { id: 'v4', size: 'L', color: 'Ivory', colorHex: '#F5F0E8', stock: 2 },
      { id: 'v5', size: 'XL', color: 'Ivory', colorHex: '#F5F0E8', stock: 1 },
    ],
    _count: { reviews: 34 },
  },
  {
    id: 'p2',
    name: 'Rose Gold Co-ord Set with Dupatta',
    slug: 'rose-gold-coord-set-dupatta',
    sku: 'HFZ-CRD-001',
    price: 3299,
    comparePrice: 5499,
    totalStock: 8,
    isNewArrival: true,
    isBestSeller: true,
    isFeatured: true,
    isTrending: true,
    avgRating: 4.9,
    category: { name: 'Co-ord Sets' },
    images: [
      { url: 'https://images.unsplash.com/photo-1608748010899-18f300247112?w=600&auto=format&fit=crop&q=80', alt: 'Rose Gold Co-ord Set' },
    ],
    variants: [
      { id: 'v6', size: 'S', color: 'Rose Gold', colorHex: '#C4748A', stock: 2 },
      { id: 'v7', size: 'M', color: 'Rose Gold', colorHex: '#C4748A', stock: 3 },
      { id: 'v8', size: 'L', color: 'Rose Gold', colorHex: '#C4748A', stock: 3 },
    ],
    _count: { reviews: 52 },
  },
  {
    id: 'p3',
    name: 'Floral Printed Cotton Kurti',
    slug: 'floral-printed-cotton-kurti',
    sku: 'HFZ-KRT-001',
    price: 899,
    comparePrice: 1499,
    totalStock: 45,
    isNewArrival: false,
    isBestSeller: true,
    isFeatured: false,
    isTrending: true,
    avgRating: 4.6,
    category: { name: 'Kurtis' },
    images: [
      { url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80', alt: 'Floral Kurti' },
    ],
    variants: [
      { id: 'v9', size: 'XS', color: 'Peach', colorHex: '#FFCBA4', stock: 8 },
      { id: 'v10', size: 'S', color: 'Peach', colorHex: '#FFCBA4', stock: 12 },
      { id: 'v11', size: 'M', color: 'Peach', colorHex: '#FFCBA4', stock: 10 },
      { id: 'v12', size: 'L', color: 'Peach', colorHex: '#FFCBA4', stock: 8 },
      { id: 'v13', size: 'XL', color: 'Peach', colorHex: '#FFCBA4', stock: 5 },
      { id: 'v14', size: 'XXL', color: 'Peach', colorHex: '#FFCBA4', stock: 2 },
    ],
    _count: { reviews: 128 },
  },
  {
    id: 'p4',
    name: 'Designer Anarkali Stitched Suit',
    slug: 'designer-anarkali-stitched-suit',
    sku: 'HFZ-STT-001',
    price: 4999,
    comparePrice: 7999,
    totalStock: 5,
    isNewArrival: true,
    isBestSeller: false,
    isFeatured: true,
    isTrending: false,
    avgRating: 4.7,
    category: { name: 'Stitched Suits' },
    images: [
      { url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80', alt: 'Anarkali Suit' },
    ],
    variants: [
      { id: 'v15', size: 'S', color: 'Burgundy', colorHex: '#800020', stock: 1 },
      { id: 'v16', size: 'M', color: 'Burgundy', colorHex: '#800020', stock: 2 },
      { id: 'v17', size: 'L', color: 'Burgundy', colorHex: '#800020', stock: 2 },
    ],
    _count: { reviews: 19 },
  },
  {
    id: 'p5',
    name: 'Pure Georgette Unstitched Suit Material',
    slug: 'pure-georgette-unstitched-suit',
    sku: 'HFZ-UNS-001',
    price: 1799,
    comparePrice: 2999,
    totalStock: 30,
    isNewArrival: false,
    isBestSeller: true,
    isFeatured: false,
    isTrending: true,
    avgRating: 4.5,
    category: { name: 'Unstitched Suits' },
    images: [
      { url: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&auto=format&fit=crop&q=80', alt: 'Georgette Suit' },
    ],
    variants: [
      { id: 'v18', size: 'Free Size', color: 'Teal', colorHex: '#008080', stock: 10 },
      { id: 'v19', size: 'Free Size', color: 'Mint', colorHex: '#98FF98', stock: 10 },
      { id: 'v20', size: 'Free Size', color: 'Navy', colorHex: '#003153', stock: 10 },
    ],
    _count: { reviews: 67 },
  },
  {
    id: 'p6',
    name: 'Embroidered Silk Chikankari Suit',
    slug: 'embroidered-silk-chikankari-suit',
    sku: 'HFZ-CHK-002',
    price: 5999,
    comparePrice: 9999,
    totalStock: 3,
    isNewArrival: true,
    isBestSeller: false,
    isFeatured: true,
    isTrending: false,
    avgRating: 5.0,
    category: { name: 'Chikankari' },
    images: [
      { url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80', alt: 'Silk Chikankari' },
    ],
    variants: [
      { id: 'v21', size: 'S', color: 'Pastel Pink', colorHex: '#FFB7C5', stock: 1 },
      { id: 'v22', size: 'M', color: 'Pastel Pink', colorHex: '#FFB7C5', stock: 1 },
      { id: 'v23', size: 'L', color: 'Pastel Pink', colorHex: '#FFB7C5', stock: 1 },
    ],
    _count: { reviews: 8 },
  },
  {
    id: 'p7',
    name: 'Festive Palazzo Kurti Set',
    slug: 'festive-palazzo-kurti-set',
    sku: 'HFZ-KRT-002',
    price: 1599,
    comparePrice: 2499,
    totalStock: 20,
    isNewArrival: false,
    isBestSeller: true,
    isFeatured: false,
    isTrending: true,
    avgRating: 4.4,
    category: { name: 'Kurtis' },
    images: [
      { url: 'https://images.unsplash.com/photo-1611601679655-7c8bc197f0c6?w=600&auto=format&fit=crop&q=80', alt: 'Palazzo Kurti' },
    ],
    variants: [
      { id: 'v24', size: 'S', color: 'Yellow', colorHex: '#FFD700', stock: 5 },
      { id: 'v25', size: 'M', color: 'Yellow', colorHex: '#FFD700', stock: 8 },
      { id: 'v26', size: 'L', color: 'Yellow', colorHex: '#FFD700', stock: 5 },
      { id: 'v27', size: 'XL', color: 'Yellow', colorHex: '#FFD700', stock: 2 },
    ],
    _count: { reviews: 89 },
  },
  {
    id: 'p8',
    name: 'Royal Blue Sharara Co-ord Set',
    slug: 'royal-blue-sharara-coord-set',
    sku: 'HFZ-CRD-002',
    price: 3799,
    comparePrice: 5999,
    totalStock: 7,
    isNewArrival: true,
    isBestSeller: false,
    isFeatured: true,
    isTrending: true,
    avgRating: 4.8,
    category: { name: 'Co-ord Sets' },
    images: [
      { url: 'https://images.unsplash.com/photo-1561414927-6d86591d0c4f?w=600&auto=format&fit=crop&q=80', alt: 'Blue Sharara' },
    ],
    variants: [
      { id: 'v28', size: 'XS', color: 'Royal Blue', colorHex: '#4169E1', stock: 1 },
      { id: 'v29', size: 'S', color: 'Royal Blue', colorHex: '#4169E1', stock: 2 },
      { id: 'v30', size: 'M', color: 'Royal Blue', colorHex: '#4169E1', stock: 3 },
      { id: 'v31', size: 'L', color: 'Royal Blue', colorHex: '#4169E1', stock: 1 },
    ],
    _count: { reviews: 23 },
  },
];

export const mockReviews = [
  {
    id: 'r1',
    name: 'Priya Sharma',
    rating: 5,
    title: 'Absolutely stunning quality!',
    body: 'I ordered the Chikankari kurta for my sister\'s wedding and received so many compliments. The fabric is luxurious and the embroidery is intricate. Will definitely order again!',
    product: 'Ivory Chikankari Kurta',
    location: 'Delhi, India',
    date: '2 weeks ago',
  },
  {
    id: 'r2',
    name: 'Fatima Khan',
    rating: 5,
    title: 'Perfect for every occasion',
    body: 'The Co-ord Set is exactly as described. Loved the color, the fit is perfect and the dupatta is gorgeous. Fast shipping too! PLT Creation has become my go-to for ethnic wear.',
    product: 'Rose Gold Co-ord Set',
    location: 'Mumbai, India',
    date: '1 month ago',
  },
  {
    id: 'r3',
    name: 'Ananya Patel',
    rating: 4,
    title: 'Beautiful kurti at great value',
    body: 'Ordered the floral kurti and it arrived in beautiful packaging. The cotton is breathable and perfect for summer. Sizing is accurate — I\'m a size M and ordered M, fits perfectly.',
    product: 'Floral Printed Kurti',
    location: 'Ahmedabad, India',
    date: '3 weeks ago',
  },
  {
    id: 'r4',
    name: 'Meera Reddy',
    rating: 5,
    title: 'PLT Creation never disappoints!',
    body: 'This is my 4th purchase from PLT Creation. The quality is consistently excellent. The packaging is premium, delivery is fast, and returns are hassle-free. Love this brand!',
    product: 'Designer Anarkali Suit',
    location: 'Hyderabad, India',
    date: '1 week ago',
  },
  {
    id: 'r5',
    name: 'Sana Mirza',
    rating: 5,
    title: 'Exceeded my expectations!',
    body: 'The fabric quality of the unstitched suit is outstanding. Got it stitched from my local tailor and it looks like it came from a high-end boutique. Truly premium ethnic wear.',
    product: 'Pure Georgette Suit',
    location: 'Lucknow, India',
    date: '5 days ago',
  },
  {
    id: 'r6',
    name: 'Riya Bose',
    rating: 4,
    title: 'Lovely designs, quick delivery',
    body: 'Ordered for Eid and it arrived 3 days before the event. The Chikankari work is so detailed and beautiful. Would have given 5 stars but the dupatta color was slightly different from photos.',
    product: 'Embroidered Silk Suit',
    location: 'Kolkata, India',
    date: '2 months ago',
  },
];

export const mockCollections = [
  {
    id: 'col1',
    name: 'Eid Festive Edit',
    slug: 'eid-festive',
    description: 'Celebrate the most beautiful festival with our handpicked Eid collection',
    bannerImage: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'col2',
    name: 'Monsoon Freshness',
    slug: 'monsoon',
    description: 'Light, breathable fabrics perfect for the rainy season',
    bannerImage: 'https://images.unsplash.com/photo-1561414927-6d86591d0c4f?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'col3',
    name: 'Wedding Season',
    slug: 'wedding',
    description: 'Be the most elegant guest at every wedding this season',
    bannerImage: 'https://images.unsplash.com/photo-1583391265517-35bbdad01209?w=1200&auto=format&fit=crop&q=80',
  },
];
